/* config.h.cmake — generated by CMake, do not edit directly.
   This mirrors the autoheader-generated config.h used by the Autotools build. */

#ifndef CONFIG_H
#define CONFIG_H

/* Package info */
#define PACKAGE "@PACKAGE_NAME@"
#define VERSION "@PACKAGE_VERSION@"
#define PACKAGE_STRING "@APP_NAME@-@PACKAGE_VERSION@"

/* Enable Native Language Support (Gettext) */
#define ENABLE_NLS 1

/* Define to 1 if you have the libxml-2.0 library */
#define HAVE_LIBXML2 1

/* Define to 1 if you have the t4k_common library */
#define HAVE_LIBT4K_COMMON 1

/* Define to 1 if libRSVG is available */
#cmakedefine01 HAVE_RSVG

/* Define to 1 if espeak or espeak-ng is available */
#cmakedefine01 WITH_ESPEAK
#cmakedefine01 WITH_ESPEAK_NG

/* Define to 1 if building natively on MinGW/Windows */
#cmakedefine01 BUILD_MINGW32

/* Standard headers */
#cmakedefine HAVE_DIRENT_H
#cmakedefine HAVE_UNISTD_H
#cmakedefine HAVE_ICONV_H
#cmakedefine HAVE_LIBINTL_H
#cmakedefine HAVE_LOCALE_H
#cmakedefine HAVE_WCHAR_H

/* Standard functions */
#cmakedefine HAVE_SCANDIR
#cmakedefine HAVE_STRCASECMP
#cmakedefine HAVE_STRNCASECMP
#cmakedefine HAVE_STRCASESTR

#endif /* CONFIG_H */
